
services:
  api:
    image: spring-boot-techchallenge
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: techchallenge_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase: